### ISSUE TITLE
Questions regarding copula correction method

### ISSUE THREAD

**Issue by awayt039** [mmeierer/REndo#32]
First off, I wanted to thank you for taking the time to write and maintain the REndo package on CRAN. This was my first introduction to instrument free methods and am interested/excited to learn more! Specifically, I took an interest in the implementation of your copula correction method and had a couple of questions that I was wondering if you could answer

1)	Are there acceptable guidelines to the implementation of copula correction methods for panel data? As a work around, I had been mean differencing/first differencing the data on my own prior to running the copula correction, but I was curious if there were better methods? Should the generated regressor used to deal with endogeneity be generated in level (undifferenced) space or first or mean differenced space? Or does it matter?
2)I noticed the ML implementation vastly improves the efficiency of the estimates (e.g. the standard errors shrink) compared to the OLS implementation. Is this normal? Do you know of a way to improve the efficiency of the OLS estimate? Further, I took a peak at the Park’s paper that formulates copula correction methods, and I was curious if you knew of a log likelihood written out for multiple endogenous covariates?

Any help you would be able to provide would be greatly appreciated. Thanks once again!

**Comment by Rgui** [comment]
Hi and thank you for your interest in REndo.

1. Regarding your question of using copulaCorrection, the only assumption of the method is that the endogenous regressor is not normally distributed. If this is true in your setting, you can try to apply it to panel data, even though I have not used it myself in such a context. First-differencing your data should not impact the results as long as the assumption above is met. Regarding the generated regressor, this is done automatically, unless you decided to create it yourself using the copulaPstar() function - but again, you have to be sure that the non-normality assumption of the endogenous regressor is met.

2. The std. errors in the ML estimation are obtained running 1000 bootstrapts, so I think it is normal for the std errors to shrink and be better than the OLS. Regarding an ML implementation for 2 or more endogenous regressors, no, it is not possible since no identification is possible. But you can use the copulaCorrection() function which in the case of more than 2 endogenous regressors uses an augmented OLS approach.

Thank you again for using REndo!
