### ISSUE TITLE
Rd files need updates for HTML5

### ISSUE THREAD

**Issue by Rgui** [mmeierer/REndo#67]
The current development version of R has recently switched to use HTML5
for documentation pages (PR#18149).  Now validation using HTML tidy
finds the following problems in your Rd files (problems only shown once
per Rd file):

REndo::copulaCorrection.Rd: Warning: <center> element removed from HTML5
REndo::hetErrorsIV.Rd: Warning: <center> element removed from HTML5
REndo::higherMomentsIV.Rd: Warning: <center> element removed from HTML5
REndo::higherMomentsIV.Rd: Warning: <div> attribute "align" not allowed for HTML5
REndo::latentIV.Rd: Warning: <center> element removed from HTML5
REndo::multilevelIV.Rd: Warning: <center> element removed from HTML5
REndo::vcov.rendo.boots.Rd: Warning: <center> element removed from HTML5
REndo::vcov.rendo.boots.Rd: Warning: unescaped & or unknown entity "̅-"

Can you please fix as necessary?

The problems reported are one of

  Warning: <center> element removed from HTML5
  Warning: <font> element removed from HTML5
  Warning: <big> element removed from HTML5

  Warning: <table> attribute "align" not allowed for HTML5
  Warning: <div> attribute "align" not allowed for HTML5
  Warning: <p> attribute "align" not allowed for HTML5
  Warning: <tr> attribute "align" not allowed for HTML5

See <https://html.spec.whatwg.org/#obsolete-but-conforming-features> for
info on these: in principle, all can be fixed by using style attributes,
e.g.

  style='text-align: right;'

instead of align='right' etc., which will work for both the new and old
ways of converting Rd to HTML.

Please fix before 2022-03-15 to safely retain your package on CRAN.

**Comment by pschil** [comment]
In separate report also: 

REndo::vcov.rendo.boots.Rd: Warning: unescaped & or unknown entity "&#773"

**Comment by pschil** [comment]
According to this official blog post ([Link](https://developer.r-project.org/Blog/public/2022/04/08/enhancements-to-html-documentation/)) and the current R CMD checks code ([Link](https://svn.r-project.org/R/trunk/src/library/tools/R/check.R)), 
these tests for tidy html5 do exist (`check_Rd2HTML`) but are not executed for documentation written with roxygen2. 
Because all docu for REndo is written with roxygen2, the docu is currently not checked for untidy html5. 
I have nevertheless fixed these issues to the best of my knowledge, without being able to verify that it is actually fixed.
